name: Setup
inputs:
  node-version:
    type: string
    require: false
    default: 18.x
  install-deps:
    type: boolean
    require: false
    default: true
runs:
  using: composite
  steps:
    - name: Use Node.js ${{inputs.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node-version}}
        cache: 'pnpm'
    - uses: pnpm/action-setup@master
      with:
        run_install: false
    # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install
      shell: bash
