name: trunk

on:
  push:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [10.x, 12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn -s test
  #
  # todo uncomment me
  # publish:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Get all git commits and tags
  #       run: git fetch --prune --unshallow --tags
  #     - uses: actions/setup-node@v1
  #     - name: Install deps
  #       run: yarn --frozen-lockfile
  #     - name: Make release
  #       id: release
  #       env:
  #         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #       run: |
  #         yarn -s dripip preview --json > result.json
  #         echo '==> Publish Result'
  #         jq '.' < result.json
